name: tarsier_logger
description:  A simple and customizable logger for Dart applications with colorized outputs and dynamic formatting.
version: 1.0.0
homepage: https://github.com/marianz-bonfire/tarsier_logger
repository: https://github.com/marianz-bonfire/tarsier_logger
issue_tracker: https://github.com/marianz-bonfire/tarsier_logger/issues

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  macos:
  web:
  windows:
  linux:

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0