name: tarsier_logger
description:  A simple and customizable logger for Dart applications with colorized outputs and dynamic formatting.
version: 1.0.3
homepage: https://github.com/marianz-bonfire/tarsier_logger
repository: https://github.com/marianz-bonfire/tarsier_logger
issue_tracker: https://github.com/marianz-bonfire/tarsier_logger/issues

topics:
  - tarsier
  - cli
  - logger
  - console

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  macos:
  web:
  windows:
  linux:

environment:
  sdk: ^3.2.1

# Add regular dependencies here.
dependencies:
# path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0

screenshots:
  - description: The package logo.
    path: assets/logo.png